# Generated by Django 3.1.5 on 2021-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeem',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='employee/photos', verbose_name='Фото'),
        ),
    ]
