# Generated by Django 3.1.5 on 2021-01-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeem',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='employee/photos'),
        ),
    ]
